apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: order-secrets
  namespace: polystore
spec:
  encryptedData:
    postgres-password: AgBJPm4ygBv2eOqNyrJ7Q3oTjdBCqtRQg6hF8ZeEeP6vDt7HP4EvT2v4W7wtfGv6GUznz7U3SJSRS3n8oPvxLTBc4jYRWoJmmhLTlCH9dzRLuZbfaLm69k7IDpmar14d3gcFXL/94dJhB6CEdms7xovE4zqSGrCnvdJ3bZx5S5gU4+WJOHPnwqLNHQpbXMSxUlf0eQC7NDPvRBQLHv+1S4qRmydhB0Bbhrtx4YB6MZ2Z+Wfk3JSa1XH54o669bmUUec/3kY4xp8f2I5iCJiMpSlxGFaLPm2ShugcnagXHakMbu7FWlEOOwziJPGPgzUlI8nWGEKUX3RYODkv9zMraobI1LhF2GkO5yJjf2mwrLSxViil8Ne73q4fWUp5rRK+EIWGq2TVlWVZ5HydVYmIOtR7Slcx4P0PJV3UmP76ox3Ff4Y7FKd82uSdiWlOzUl0eyGApdBB98zEmwwB3Bkwy/P4fALgigSgB+GKCj0L8uqmbzgoVFbiiNrRAzN1LywqkLWlMhsPGbJ9vCvp6lnXTJt7L0mgvklaBEsW6rXPl/Q2EdPn0wXk6e6PM1uYjh1C2U+YPSJ33iuac7vmRa0rSsseCaeYc3XfDCfph0DybdZtJ6RQyK3Q8AK6wmbnCdg4sRITe3SeyeGA6gx3eqqEmXi+PbN3Rq9xzPczFofG3lJ1XSEBHMVPjbiXmLoTvQhKFSTLS9FIng==
  template:
    metadata:
      creationTimestamp: null
      name: order-secrets
      namespace: polystore
    type: Opaque

