apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-admin
  namespace: polystore
spec:
  encryptedData:
    postgres-password: AgAFBqS7PtF+QidBu5s1rPpAYs7XQ0NZpRehmSZgMcEt+CVlWVd4pzvAGs6/Ay7xAhhSMqALz6ZVOq3eUd/llFRG0A4Szq/3+vIrKWLOaBhj8WMMgCnF4KUT4WQHK+fY0JUQLvFUHCElytOXJ7nPIqOpNzlhT10+0xlzZlYBLPJ57y+2afAHxVl98pqfc+qxD0pdk1/R1ApGkveAuKdIkd6ZSi7BvgC+rXT9b58fxggPn2mbqpo9jH37CeaSs5IyBbInZx4IjfNA5OHG6lA+rWx4YyfELQfpV1/JxDhScv8RBCMhbgNHvPt+JGdScMHgcywSEZTo9DYboBXsqng5lJal+N9/hwhmF9C0aNpIqWAesRorWMCaj1G5hmxcSSiTVkJxQdzo31eNzSlma4ajetX9N0FyuEuBX/uhnaeUJxbLsDClDWhLCV4mnIaUzfIHHSlBtTBQ9Y4U9JX3VCKc145Vo8X0qizlZSR4gTjSlmNPavdzyQQXe9gUna7WuN9w7tp40954BOd3iFL8K76AaiI/JOPw5+m34xwFugqlLmPMxebvlEtUkgZB3BX5dykgKtTFSi/JlSHPcrpSN8HGGWuIUT9+YYA2TwbeWOe2R9vZXcC2sgFsXIMZSKGQcxzFFDlPfY8yX0ZxCzTYQjNgHxSS9SLitKrVvCnGOHuLFxahaFEK5HwsMEQfwNfVMudl8jSjnfOD0qiH6w==
  template:
    metadata:
      creationTimestamp: null
      name: postgres-admin
      namespace: polystore
    type: Opaque

