apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rabbitmq-password
  namespace: polystore
spec:
  encryptedData:
    rabbitmq-password: AgBxcFcQBgg1zWTJrZpNS+hC/yVFXqaM2R2fJ0Mxbepfsw4bvILqXDcg17E6kBm9bGxmApQBi54dCxJz9hbliCN1+AMYRlMnj3GFsCsVx6hAwSIBDV/BcMWN9vn2+dMehftg590bzDDWipuUq/wa8Ul2S8TjF8TYv4ga4Sm04UYEiyOMWeEBEBIeRL4NHLFBW4/yuanHMJjqAacOALgs6jF34t3eh9ZE6LzYXJ+GqbSOF//s3WGvvhgl3FI4F5RCwGp4tpDjwXnBrAI2smqGcn1HDsBCB3c53AhKRWdaeI2CbPEyC2sRuR0fJ2pnZ9CuRBa6L6EIUamikxxqCnAXkCheHLAbI6YTymkug1mjOR9f++lFx1ZQdzhtu9m+vpXQ0Ptqwky/sSG1dPugd2LLTBh9pcY2F60u9sS3PwTvh0edGsuYa6dnja+ZdH98VyRCUPZFztbWzl7olKOW/enS347R/AR5XYgoSsP7WAu3NBVAWG5ZeHqjpTSOsJ9Pa15lMSYEX/cC4eiyjNeE//K0/IhV0RhaoBRMWHCD98L3//VDzIzG22myLVmpe9G9Marj6L6+SxspkpapXA6v1soUAkltTAc9H7UjG/25aty8qi1d1afCu0exza6LJqqh0W9aLACAskO29G0s7et5YZPURndeAooyBZgxgx9YtxhofzXlVPFCt8tS2dbBHkzK1RHq7f5Af0cnXA==
  template:
    metadata:
      creationTimestamp: null
      name: rabbitmq-password
      namespace: polystore
    type: Opaque

