apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: rabbitmq-password
  namespace: polystore
spec:
  encryptedData:
    rabbitmq-password: AgBZe9u2mL+e+I7aZc6cw1OSqUXEz8rp7yORQQXA1BPt7PvMFLOSuH35DsSf0xon5sO3hbdIIX20r8MoxCXK3HjGjT4C7yu61O6dV7jMEyYDkxv6veX7oNiF42DH7Alv0aXQOaOeLz0HaOhJpOX3Ydks5gBlcCoZCOEQRh/X/VgDohSsh6BXWTOWVJm/+j2C1wc8Y7tVFDpghOV09Mo+S1XkTuxZ5QruOWD8aYfILmHNLZeZw7OQF+Y3ECNYccYacKc6SdjLcAJynG9vpq7hsswoij/5iofI6Y3NPMsmwY0UtuGz95pKQx84z0jYLL1VJYRbWoVY5bJ+Cia4/iwm2Hby0Lyg2vFBNNE5a3BMpcoEcrEu4N0509b95+uNBi8tnYLWF77WopxjnXK330rbEoraBbnDG4TY2CVzRESgNg4LHHAaI2UgvdENBUmg7YwYF/EYzDWslGCaNuRv0Z0BL/lz6kqzf2TBWx0Zu0duzZVqerFQP8K/J/sAKQC1y5zI1TieQWCu2dHuD+X1ovd6OGvjolRhJreUCxtgc3POqEAC4UxpIj9GrKLdV64DqYYhc+BtuRqcbUxS8XXyrCKapQxZZ8cbAwLlpit5HS8EMLogPi7zzQYCzobYsMZZP/r5mYHZUR/Vy34IBMgdfVTARuupc3pxaC4UN1YofN3z+Ro8RpjwMYcclTFWgim2DGz/1hfbams7Fw==
  template:
    metadata:
      creationTimestamp: null
      name: rabbitmq-password
      namespace: polystore
    type: Opaque

