version: '3.7'
services:
  mongo:
    image: mongo:4.0.4
    ports:
      - "27017:27017"

  redis:
    image: redis
    ports:
      - "6379:6379"

  postgres-order:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: polystore
      PGDATA: ./data/db/postgres

  postgres-inventory:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: polystore
      PGDATA: ./data/db/postgres

  postgres-payment:
    image: postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: polystore
      PGDATA: ./data/db/postgres

  rabbitmq:
    image: 'bitnami/rabbitmq:latest'
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
        RABBITMQ_USERNAME: simon
        RABBITMQ_PASSWORD: simon
