version: '3.7'
services:
  mongo:
    image: mongo:4.0.4
    ports:
      - "27017:27017"

  redis:
    image: redis
    ports:
      - "6379:6379"

  postgres-order:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: polystore
      PGDATA: ./data/db/postgres

  postgres-inventory:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: polystore
      PGDATA: ./data/db/postgres

  postgres-payment:
    image: postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: polystore
      PGDATA: ./data/db/postgres

  postgres-shipping:
    image: postgres
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: polystore
      PGDATA: ./data/db/postgres

  rabbitmq:
    image: 'bitnami/rabbitmq:latest'
    ports:
      - '5552:5552'
      - '5672:5672'
      - '15672:15672'
    environment:
        RABBITMQ_USERNAME: simon
        RABBITMQ_PASSWORD: simon

  zookeeper:
    image: 'confluentinc/cp-zookeeper:6.2.1'
    ports:
      - '2181:2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: 'confluentinc/cp-kafka:6.2.1'
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: 'false'

  kafka-ui:
    image: 'provectuslabs/kafka-ui:latest'
    ports:
      - '9090:8080'
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'