apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    app: gateway
    service: gateway
spec:
  type: NodePort 
  ports:
    - nodePort: 30080
      port: 9090
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: gateway
