apiVersion: v1
kind: Service
metadata:
  name: inventory
  labels:
    app: inventory
    service: inventory
spec:
  ports:
    - port: 80
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
      name: http
  selector:
    app: inventory
