apiVersion: k3d.io/v1alpha4
kind: Simple
network: polystore
ports:
  - port: 8083:80
    nodeFilters:
      - loadbalancer
options:
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - servers:*
