apiVersion: v1
kind: Service
metadata:
  name: shipping
  labels:
    app: shipping
    service: shipping
spec:
  ports:
    - port: 80
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
      name: http
  selector:
    app: shipping
