{{- if .Values.sealedSecrets }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: order-secrets
spec:
  encryptedData:
    {{- if .Values.sealedSecrets.postgres }}
    postgres-password: {{ .Values.sealedSecrets.postgres.password | quote }}
    {{- end }}
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: order-secrets
{{- end }}
